### ISSUE TITLE
Funcionar WIFI

### ISSUE THREAD

**Issue by lucianomartinsjr** [wendersonrodrigues/EFI-DELL-5378-2EM1-I7-7500U-INTELHD620#1]
Opa Wenderson!

Está sendo de grande ajuda para me basear e ajustar, tenho o mesmo note, porém não estou conseguindo fazer o wifi funcionar, eu tenho a DELL DW1560 (BCM94352Z), será que consegue me dar uma ajuda?

**Comment by wendersonrodrigues** [comment]
Qual o modelo da sua placa do wifi? no caso dependendo do modelo a placa original do wifi + bluetooth realmente não funcionarão, talvez você terá que adquirir a placa da Venfi.

**Comment by wendersonrodrigues** [comment]
Acredito que esse modelo não é compativel, te aconselho adquirir o modelo: Fenvi Bcm94360ng, para que funcione o Wifi + Bluetooth + Airdrop

**Comment by wendersonrodrigues** [comment]
Amigo essa placa que você citou funciona só até o macOS Monterey, infelizmente para funcionar nativamente com o macOS Ventura você terá que adquirir o modelo: Fenvi Bcm94360ng
